### ISSUE TITLE
[BUG] ElinConnect shows error and cannot make connection.

### ISSUE THREAD

**Issue by Peeeaje** [liquidz/elin#12]
**Describe the bug**
ElinConnect shows error and cannot connect to repl.
Error message: `Failed to intercept for :elin.constant.interceptor/connect: error occured on entering elin.interceptor.connect.shadow-cljs/detect-shadow-cljs-port because of 'null'`

**To Reproduce**
Lunch repl by below command. (From the doc)
```shell

$ clj -Sdeps '{:deps {nrepl/nrepl {:mvn/version "1.3.0"} cider/cider-nrepl {:mvn/version "0.50.3"}}}' -M -m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware]" --interactive

```
Open a clojure file and call :ElinConnect in neovim.

**Expected behavior**
I can make connection to running repl.

**Environemnt (please complete the following information):**
 - Editor: Neovim
 - Editor version: 0.10.2 
 - Babashka version: 1.12.195

**Comment by liquidz** [comment]
@Peeeaje Sorry for late reply. I'll have a look.

**Comment by liquidz** [comment]
@Peeeaje The error seems to occur in files that are not managed by git. I'll fix it :)

**Comment by liquidz** [comment]
@Peeeaje I've fixed the problem. Could you try the latest version?

**Comment by Peeeaje** [comment]
I confirmed it is working now!! Thank you. :)
