### ISSUE TITLE
[BUG] Keymap keep existing even after removing plugin

### ISSUE THREAD

**Issue by Peeeaje** [liquidz/elin#13]
**Describe the bug**
Even after removing elin plugin, set keymaps by enabling `elin_enable_default_key_mappings` continues to exist...

**To Reproduce**
1. use neovim and lazy.nvim
1. install elin with enabling `elin_enable_default_key_mappings`
1. remove the plugin
1. see keymaps by `:map` 

**Expected behavior**
keymap removed when disabled or deleted

**Environemnt (please complete the following information):**
- Editor: Neovim
- Editor version: 0.10.2
- Babashka version: 1.12.195

**Additional context**
I often use neovim plugin rather vim plugin so such keymap remaining can be normal or maybe your expected behavior. If so please close this. :)
Also I have not fully investigated the situation so it might not be reproduced by above, if so I will find minimum config/steps to reproduce. Thank you.

**Comment by liquidz** [comment]
@Peeeaje 
The keymap will not be registered unless the plugin remains in neovim's runtimepath.
So I suspect lazy.nvim is caching something.

Please try checking the current runtimepath with `:set rtp`.  
If there is anything related to elin left, could you clear the cache on the lazy.nvim side.

cf. https://github.com/folke/lazy.nvim/issues/29

**Comment by liquidz** [comment]
Feel free to reopen if you have any other problems :)
